services:
  samwaf:
    image: ghcr.io/lanqiguoguo/samwaf:v1.3.24
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${PANEL_APP_PORT_HTTP}:26666"
      - "${PANEL_APP_PORT_HTTP1}:80"
      - "${PANEL_APP_PORT_HTTPS2}:443"
    volumes:
      - ./conf:/app/conf
      - ./data:/app/data
      - ./logs:/app/logs
      - ./ssl:/app/ssl
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
