services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:v3.2.8
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    # hostname: yourhostname <- optional
    # default_port <- 2053
    # default_username <- admin
    # default_password <- admin
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=false
      - TZ=${TIME_ZONE}
    tty: true
    restart: unless-stopped
    network_mode: host
    command:
      - |
        if [ ! -f /etc/x-ui/x-ui.db ]; then
          /app/x-ui & sleep 5 && kill $!
        fi
        /app/x-ui setting -port ${PANEL_APP_PORT_HTTP}
        /app/x-ui setting -webBasePath ${PANEL_WEB_BASE_PATH}
        /app/x-ui setting -username ${PANEL_USERNAME}
        /app/x-ui setting -password ${PANEL_PASSWORD}
        exec /app/DockerEntrypoint.sh
    labels:
      createdBy: "Apps"