services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:v3.2.8
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    # hostname: yourhostname <- optional
    # default_port <- 2053
    # default_sub_port <- 2096
    # default_username <- admin
    # default_password <- admin
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=false
      - TZ=${TIME_ZONE}
    tty: true
    ports:
      - "${PANEL_APP_PORT_HTTP}:2053"
      - "${PANEL_APP_SUB_PORT_HTTP}:2096"
    restart: unless-stopped
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true