services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:v7.2.67
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/CLIProxyAPI/auths
      - ./logs:/CLIProxyAPI/logs
      - ./plugins:/CLIProxyAPI/plugins
    ports:
      - ${PANEL_APP_PORT_HTTP}:8317
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true