services:
  openresty:
    image: openresty/openresty:1.31-alpine-slim
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d:ro
      - ./html:/usr/local/openresty/nginx/html
      - ./log:/usr/local/openresty/nginx/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true
