services:
  cypht:
    image: cypht/cypht:2.11.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - TZ=${PANEL_APP_TIME_ZONE}
      - AUTH_USERNAME=${PANEL_AUTH_USERNAME}
      - AUTH_PASSWORD=${PANEL_AUTH_PASSWORD}
      - DB_DRIVER=pgsql
      - DB_CONNECTION_TYPE=host
      - DB_HOST=${PANEL_DB_HOST}
      - DB_NAME=${PANEL_DB_NAME}
      - DB_USER=${PANEL_DB_USER}
      - DB_PASS=${PANEL_DB_PASSWORD}
      - SESSION_TYPE=Redis
      - USER_CONFIG_TYPE=DB
      - AUTH_TYPE=DB
      - ENABLE_REDIS=true
      - REDIS_SERVER=${PANEL_REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASS=${PANEL_REDIS_PASSWORD}
      - REDIS_INDEX=1
      - DEFAULT_LANGUAGE=zh-Hans
      - DEFAULT_SETTING_LANGUAGE=zh-Hans
      - DEFAULT_SETTING_TIMEZONE=${PANEL_APP_TIME_ZONE}
      - OUTLOOK_CLIENT_ID=${PANEL_OUTLOOK_CLIENT_ID}
      - OUTLOOK_CLIENT_SECRET=${PANEL_OUTLOOK_CLIENT_SECRET}
      - OUTLOOK_CLIENT_URI=${PANEL_OUTLOOK_CLIENT_URI}
      - OUTLOOK_AUTH_URI=https://login.live.com/oauth20_authorize.srf
      - OUTLOOK_TOKEN_URI=https://login.live.com/oauth20_token.srf
      - OUTLOOK_REFRESH_URI=https://login.live.com/oauth20_token.srf
      - GMAIL_CLIENT_ID=${PANEL_GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${PANEL_GMAIL_CLIENT_SECRET}
      - GMAIL_CLIENT_URI=${PANEL_GMAIL_CLIENT_URI}
      - GMAIL_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - GMAIL_TOKEN_URI=https://www.googleapis.com/oauth2/v3/token
      - GMAIL_REFRESH_URI=https://www.googleapis.com/oauth2/v3/token
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ./data:/var/lib/hm3
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true