services:
  cypht:
    image: cypht/cypht:2.11.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - TZ=${PANEL_APP_TIME_ZONE}
      - AUTH_USERNAME=${PANEL_AUTH_USERNAME}
      - AUTH_PASSWORD=${PANEL_AUTH_PASSWORD}
      - DB_DRIVER=pgsql
      - DB_CONNECTION_TYPE=host
      - DB_HOST=${PANEL_DB_HOST}
      - DB_NAME=${PANEL_DB_NAME}
      - DB_USER=${PANEL_DB_USER}
      - DB_PASS=${PANEL_DB_PASSWORD}
      - SESSION_TYPE=Redis
      - USER_CONFIG_TYPE=DB
      - AUTH_TYPE=DB
      - ENABLE_REDIS=true
      - REDIS_SERVER=${PANEL_REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASS=${PANEL_REDIS_PASSWORD}
      - REDIS_INDEX=1
      - DEFAULT_LANGUAGE=zh-Hans
      - DEFAULT_TIMEZONE=${PANEL_APP_TIME_ZONE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ./data:/var/lib/hm3
    networks:
      - 1panel-network
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true