version: '3.8'
services:
  komari:
    image: ghcr.io/komari-monitor/komari:1.2.0
    container_name: komari
    ports:
      - ${PANEL_APP_PORT_HTTP}:25774
    volumes:
      - ./data:/app/data
    environment:
    # 可选：自定义初始管理员账号
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    restart: unless-stopped
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true