version: '3.8'
services:
  outlookemail:
    image: ghcr.io/assast/outlookemail:v2.0.53
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:5000"
    volumes:
      - ./data:/app/data
    environment:
      - LOGIN_PASSWORD=${OUTLOOKEMAIL_LOGIN_PASSWORD}
      - SECRET_KEY=${OUTLOOKEMAIL_SECRET_KEY}
      - FLASK_ENV=production
    restart: unless-stopped
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true