services:
  wallos:
    container_name: ${CONTAINER_NAME}
    image: bellamy/wallos:4.3.0
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    environment:
      - TZ=${WALLOS_TZ}
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true